### ISSUE TITLE
Add colorblind feature

### ISSUE THREAD

**Issue by dutchmaste82** [MaikelStuivenberg/EncoreGameSheet#8]
Hi Maikel,

I have a idea to add as feature to your game cards. Can you add the color letters to each cell as option in settings for colorblind people?
Y - yellow
G - green
B - blue
R - red
O - orange

Mvg,

Matthew

**Comment by MaikelStuivenberg** [comment]
Hi Matthew,

That's a great idea! I'm going to take a look at it.

**Comment by dutchmaste82** [comment]
![16724295497976512048641595858506](https://user-images.githubusercontent.com/121691636/210106890-4e97f96a-c7ee-450c-9d49-63ae291a81ba.jpg)
Example of our current solution 😎

**Comment by dutchmaste82** [comment]
Works like a charm on Android, thank you so much.

Op vr 30 dec. 2022 20:41 schreef Maikel Stuivenberg <
***@***.***>:
